# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI - Build and Archive

on:
  push:
    branches:
      - "develop"
      - "feature/**"
  pull_request:
    branches:
      - "develop"
      - "feature/**"

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      matrix:
        node-version: [16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Build
        run: |
          npm ci
          npm run build --if-present
          echo "Build Complete"

      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: |
            build 

      - name: Create Distribution
        uses: thedoctor0/zip-release@0.7.5
        with:
          type: zip
          filename: 'release.zip'
          directory: build

      - name: Create Release
        uses: "marvinpinto/action-automatic-releases@latest"
        if: ${{ ( github.ref_name == 'main' || github.ref_name == 'develop' ) && startsWith( matrix.node-version, '18') }}
        with:
          repo_token: ${{ github.token }}
          prerelease: ${{ github.ref_name != 'main' }}
          automatic_release_tag: latest
          files: |
            build/release.zip



